version: '2'

services:

  audio:
    image: bh.cr/balenalabs/audio-aarch64 # where <arch> is one of rpi, armv7hf, aarch64 or amd64
    privileged: true
    labels:
      io.balena.features.dbus: 1  # Only required for bluetooth support
    ports:
      - 4317:4317                 # Only required if using PA over TCP socket
    environment:
      AUDIO_OUTPUT: RPI_HEADPHONES

  my-audio-app:
    build: ./
    environment:
      PULSE_SERVER: tcp:audio:4317
